data:
  test:
    batch_size: 8
    loader: sqpdnet
    motion_noise_augment: true
    motion_noise_std: 0.02
    num_workers: 8
    parameters_noise_augment: true
    paths:
    - datasets/unknown_2d_1
    - datasets/unknown_2d_2
    - datasets/unknown_2d_3
    - datasets/unknown_2d_4
    shuffle: false
  training:
    batch_size: 8
    loader: sqpdnet
    motion_noise_augment: true
    motion_noise_std: 0.02
    num_workers: 8
    parameters_noise_augment: true
    paths:
    - datasets/unknown_2d_1
    - datasets/unknown_2d_2
    - datasets/unknown_2d_3
    - datasets/unknown_2d_4
    shuffle: true
  validation:
    batch_size: 8
    loader: sqpdnet
    motion_noise_augment: true
    motion_noise_std: 0.02
    num_workers: 8
    parameters_noise_augment: true
    paths:
    - datasets/unknown_2d_1
    - datasets/unknown_2d_2
    - datasets/unknown_2d_3
    - datasets/unknown_2d_4
    shuffle: true
device: cuda:1
model:
  arch: sqpdnet
  motion_module:
    action:
      l_hidden:
      - 64
      - 128
      output_dim: 256
    action_dim: 5
    arch: motionnet
    dsq_dim: 13
    ego:
      l_hidden:
      - 64
      - 128
      output_dim: 256
    global_1:
      l_hidden:
      - 64
      - 128
      output_dim: 256
    global_2:
      l_hidden:
      - 256
      - 256
      output_dim: 256
    motion_dim: 2D
    motion_orientation:
      l_hidden:
      - 256
      - 256
      - 128
      - 128
      - 64
      - 64
    motion_position:
      l_hidden:
      - 256
      - 256
      - 128
      - 128
      - 64
      - 64
    num_primitives: 4
trainer:
  eval_interval: 50000
  loss:
    type: motion_loss
    weight: 0.1
  metric:
    type: motion_prediction
  n_epoch: 500
  optimizer:
    lr: 0.0005
    name: adam
  print_interval: 100
  save_interval: 100000
  type: baseline
  val_interval: 5000
  visualize_interval: 5000
