model:
  arch: sqnet
  backbone:
    arch: dgcnn
    use_spatial_transform: False
    use_mean_global_feature: False
    use_batch_norm: False
    k: 20
    leakyrelu_slope: 0.2
    input_dim: 4
    l_hidden_local: [64, 64, 128, 256]
    global_feature_dim: 1024
  position:
    l_hidden: [512, 256]
    output_dim: 3
  orientation:
    l_hidden: [512, 256]
    output_dim: 4
  size:
    l_hidden: [512, 256]
    output_dim: 3
  shape:
    l_hidden: [512, 256]
    output_dim: 2
trainer:
  type: recognition
  n_epoch: 500
  loss:
    type: sq_loss
  optimizer:
    name: 'adam'
    lr: 0.00005
  print_interval: 100
  val_interval: 5000
  save_interval: 100000
  visualize_number: 3
  visualize_interval: 100000
data:
  training:
    loader: recognition
    noise_augment: True
    noise_std: 0.001
    paths: [datasets/pushing_object_num_1, datasets/pushing_object_num_2, datasets/pushing_object_num_3, datasets/pushing_object_num_4]
    batch_size: 8
    num_workers: 8
    shuffle: True
  validation:
    loader: recognition
    noise_augment: True
    noise_std: 0.001
    paths: [datasets/pushing_object_num_1, datasets/pushing_object_num_2, datasets/pushing_object_num_3, datasets/pushing_object_num_4]
    batch_size: 8
    num_workers: 8
    shuffle: False
  test:
    loader: recognition
    noise_augment: True
    noise_std: 0.001
    paths: [datasets/pushing_object_num_1, datasets/pushing_object_num_2, datasets/pushing_object_num_3, datasets/pushing_object_num_4]
    batch_size: 8
    num_workers: 8
    shuffle: False
