realworld: false
model:
  arch: sqpdnet
  seg_module:
    path: pretrained/segmentation_config/pretrained
    checkpoint: model_best.pkl
  recog_module:
    path: pretrained/recognition_config/pretrained
    checkpoint: model_best.pkl
  motion_module:
    path: pretrained/sqpdnet_2d_motion_only_config/pretrained
    checkpoint: model_best.pkl
  enable_gui: true
  calibration_k: 25
  num_pts_recog: 512
objects:
  object1:
    type: box
    XYZ: [0.04, 0.04, 0.02]
    position_xy: [0.4, -0.2]
    orientation: [0, 0, 0.923, 0.3826]
  object2:
    type: cylinder
    RH: [0.03, 0.06]
    position_xy: [0.3, 0.2]
    orientation: [0, 0, 0, 1]
  object3:
    type: cylinder
    RH: [0.05, 0.1]
    position_xy: [0.5, 0.2]
    orientation: [0, 0, 0, 1]
controller:
  evaluator:
    k: 25
    num_pts_recog: 512
  sample_num: 300
  action_horizon: 1
  criterior: moving
  goal_positions:
    goal1:
      position_xy: [0.4, -0.1]
      orientation: [0, 0, 0, 1]
    goal2:
      position_xy: [0.3, 0.1]
      orientation: [0, 0, 0, 1]
    goal3:
      position_xy: [0.5, 0.1]
      orientation: [0, 0, 0, 1]
  target_object: largest
    
  