realworld: false
model:
  arch: sqpdnet
  seg_module:
    path: pretrained/segmentation_config/pretrained
    checkpoint: model_best.pkl
  recog_module:
    path: pretrained/recognition_config/pretrained
    checkpoint: model_best.pkl
  motion_module:
    path: pretrained/sqpdnet_2d_motion_only_config/pretrained
    checkpoint: model_best.pkl
  enable_gui: true
  calibration_k: 25
  num_pts_recog: 512
objects:
  object1:
    type: box
    # XYZ: [0.07, 0.07, 0.07]
    XYZ: [0.15, 0.19, 0.045]
    # position_xy: [0.45, 0.1]
    position_xy: [0.45, 0.05]
    orientation: [0, 0, 0, 1]
  object2:
    type: cylinder
    RH: [0.03, 0.06]
    position_xy: [0.45, 0.15]
    orientation: [0, 0, 0, 1]
controller:
  evaluator:
    k: 25
    num_pts_recog: 512
  sample_num: 300
  action_horizon: 1
  criterior: moving_interactive
  goal_position:
    position_xy: [0.45, 0.3]
    orientation: [0, 0, 0, 1]
  target_object: smallest
    
  