realworld: false
model:
  arch: sqpdnet
  seg_module:
    path: pretrained/segmentation_config/pretrained
    checkpoint: model_best.pkl
  recog_module:
    path: pretrained/recognition_config/pretrained
    checkpoint: model_best.pkl
  motion_module:
    path: pretrained/sqpdnet_2d_motion_only_config/pretrained
    checkpoint: model_best.pkl
  enable_gui: true
  calibration_k: 25
  num_pts_recog: 512
objects:
  object1:
    type: box
    XYZ: [0.06, 0.06, 0.06]
    position_xy: [0.4, 0]
    orientation: [0, 0, 0, 1]
  object2:
    type: cylinder
    RH: [0.04, 0.1]
    position_xy: [0.5, 0]
    orientation: [0, 0, 0, 1]
  # object3:
  #   type: box
  #   XYZ: [0.08, 0.08, 0.08]
  #   position_xy: [0.4, 0.11]
  #   orientation: [0, 0, 0, 1]
  object4:
    type: cylinder
    RH: [0.04, 0.09]
    position_xy: [0.4, -0.1]
    orientation: [0, 0, 0, 1]
controller:
  evaluator:
    k: 25
    num_pts_recog: 512
  sample_num: 500
  action_horizon: 3
  criterior: grasp_top
  target_object: cylinder