realworld: false
model:
  arch: sqpdnet
  seg_module:
    path: pretrained/segmentation_config/pretrained
    checkpoint: model_best.pkl
  recog_module:
    path: pretrained/recognition_config/pretrained
    checkpoint: model_best.pkl
  motion_module:
    path: pretrained/sqpdnet_2d_motion_only_config/pretrained
    checkpoint: model_best.pkl
  enable_gui: true
  calibration_k: 25
  num_pts_recog: 512
objects:
  object1:
    type: box
    XYZ: [0.15, 0.19, 0.045]
    position_xy: [0.4, -0.48]
    orientation: [0, 0, 0, 1]
controller:
  evaluator:
    k: 25
    num_pts_recog: 512
  sample_num: 500
  action_horizon: 3
  criterior: grasp
  target_object: largest