realworld: true
model:
  arch: sqpdnet
  seg_module:
    path: pretrained/segmentation_config/pretrained
    checkpoint: model_best.pkl
  recog_module:
    path: pretrained/recognition_config/pretrained
    checkpoint: model_best.pkl
  motion_module:
    path: pretrained/sqpdnet_2d_motion_only_config/pretrained
    checkpoint: model_best.pkl
  enable_gui: false
  calibration_k: 25
  num_pts_recog: 512
controller:
  evaluator:
    k: 25
    num_pts_recog: 512
  sample_num: 500
  action_horizon: 3
  criterior: grasp_top
  target_object: cylinder